"""
State management module for the Data Samanvayah Agent (DSA).

This module defines the core state objects and context models used throughout 
the LangGraph workflow. It leverages Pydantic v2 for robust data validation 
and typing, and utilizes LangGraph's Annotated reducers for state accumulation.
"""

from __future__ import annotations

import operator
import uuid
from datetime import datetime, timezone
from typing import Annotated, Any, TypedDict

from pydantic import BaseModel, ConfigDict, Field, field_serializer, field_validator


# ---------------------------------------------------------------------------
# TypedDict Definitions
# ---------------------------------------------------------------------------

class Message(TypedDict):
    """Represents a single message in the workflow communication channel."""
    
    role: str
    content: str
    timestamp: str


class LogEntry(TypedDict):
    """Represents a single structured log entry."""
    
    level: str
    message: str
    timestamp: str


# ---------------------------------------------------------------------------
# Context & Metadata Models
# ---------------------------------------------------------------------------

class DatasetMetadata(BaseModel):
    """Metadata and schema information for the ingested dataset."""
    
    model_config = ConfigDict(arbitrary_types_allowed=True, populate_by_name=True)

    dataset_path: str
    dataset_name: str
    dataset_size: int
    rows: int
    columns: int
    file_type: str
    dataset_schema: dict[str, Any] = Field(alias="schema")
    missing_summary: dict[str, int]


class MemoryContext(BaseModel):
    """Context retrieved from the agent's memory system."""
    
    retrieved_runs: list[dict[str, Any]] = Field(default_factory=list)
    semantic_matches: list[dict[str, Any]] = Field(default_factory=list)
    episodic_matches: list[dict[str, Any]] = Field(default_factory=list)
    procedural_rules: list[str] = Field(default_factory=list)
    similarity_scores: dict[str, float] = Field(default_factory=dict)


class TrainingResults(BaseModel):
    """Results and artifacts from the model training phase."""
    
    model_config = ConfigDict(arbitrary_types_allowed=True)

    best_model: Any | None = None
    task_type: str | None = None
    metrics: dict[str, float] = Field(default_factory=dict)
    leaderboard: list[dict[str, Any]] = Field(default_factory=list)
    feature_importance: dict[str, float] = Field(default_factory=dict)
    training_time: float = 0.0
    artifacts: dict[str, Any] = Field(default_factory=dict)


class PlannerContext(BaseModel):
    """Context generated by the Planner agent for execution strategy."""
    
    target_column: str | None = None
    confidence: float = 0.0
    reasoning: str = ""
    suggested_models: list[str] = Field(default_factory=list)
    preprocessing_steps: list[str] = Field(default_factory=list)


class CriticContext(BaseModel):
    """Context and evaluation results from the Critic agent."""
    
    passed: bool = False
    confidence: float = 0.0
    issues_found: list[str] = Field(default_factory=list)
    retry_reason: str | None = None
    retry_count: int = 0
    recommendations: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Main LangGraph State
# ---------------------------------------------------------------------------

class DSAState(BaseModel):
    """
    Main state object for the Data Samanvayah Agent (DSA) LangGraph workflow.
    
    This model encapsulates the entire state of the execution, including 
    dataset references, agent contexts, accumulated logs/messages, and 
    execution metadata. It utilizes Pydantic v2 with full serialization 
    support for checkpointing and human-in-the-loop workflows.
    """
    
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        serialize_as_any=True,
    )

    # Core Data References
    dataset: Any | None = None
    cleaned_dataset: Any | None = None
    
    # Session Management for Checkpointing
    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    thread_id: str = Field(default_factory=lambda: f"thread_{uuid.uuid4().hex[:8]}")
    
    # Agent Contexts
    dataset_metadata: DatasetMetadata | None = None
    memory_context: MemoryContext | None = None
    planner_context: PlannerContext | None = None
    training_results: TrainingResults | None = None
    critic_context: CriticContext | None = None
    
    # Artifacts and Accumulators
    artifacts: dict[str, Any] = Field(default_factory=dict)
    logs: Annotated[list[LogEntry], operator.add] = Field(default_factory=list)
    messages: Annotated[list[Message], operator.add] = Field(default_factory=list)
    errors: Annotated[list[str], operator.add] = Field(default_factory=list)
    
    # Execution Metadata
    execution_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    user_preferences: dict[str, Any] = Field(default_factory=dict)
    
    # Workflow Control
    status: str = "initialized"
    completed_agents: list[str] = Field(default_factory=list)
    current_agent: str | None = None
    retry_counter: int = 0
    metadata: dict[str, Any] = Field(default_factory=dict)
    
    # Human-in-the-Loop Support
    pending_human_approval: bool = False
    approval_request: str | None = None

    # -------------------------------------------------------------------------
    # Helper Methods
    # -------------------------------------------------------------------------

    def reset_runtime(self) -> None:
        """
        Resets runtime-specific fields to prepare the state for a new 
        execution or retry cycle, preserving core data and metadata.
        """
        self.logs = []
        self.messages = []
        self.errors = []
        self.status = "initialized"
        self.completed_agents = []
        self.current_agent = None
        self.retry_counter = 0
        self.timestamp = datetime.now(timezone.utc)
        self.pending_human_approval = False
        self.approval_request = None

    def append_log(self, message: str, level: str = "INFO") -> None:
        """
        Appends a structured log entry to the state's log accumulator.
        
        Args:
            message: The log message content.
            level: The severity level of the log (e.g., INFO, WARNING, ERROR).
        """
        entry = LogEntry(
            level=level,
            message=message,
            timestamp=datetime.now(timezone.utc).isoformat()
        )
        self.logs.append(entry)

    def add_error(self, error: str) -> None:
        """
        Adds an error message to the state's error accumulator.
        
        Args:
            error: The error message or string representation of the exception.
        """
        self.errors.append(error)

    def mark_completed(self, agent_name: str) -> None:
        """
        Marks a specific agent as completed and clears the current agent.
        
        Args:
            agent_name: The name of the agent that has completed its task.
        """
        if agent_name not in self.completed_agents:
            self.completed_agents.append(agent_name)
        self.current_agent = None

    def update_status(self, status: str, current_agent: str | None = None) -> None:
        """
        Updates the overall execution status and optionally sets the current agent.
        
        Args:
            status: The new status string (e.g., 'running', 'paused', 'failed').
            current_agent: The name of the agent currently executing, if applicable.
        """
        self.status = status
        if current_agent is not None:
            self.current_agent = current_agent
    
    def request_human_approval(self, request: str) -> None:
        """
        Requests human approval by setting the pending flag and request message.
        Used for human-in-the-loop workflows.
        
        Args:
            request: The message to display to the human reviewer.
        """
        self.pending_human_approval = True
        self.approval_request = request
        self.status = "awaiting_approval"
    
    def approve_and_continue(self) -> None:
        """
        Clears the human approval flags to allow workflow to continue.
        """
        self.pending_human_approval = False
        self.approval_request = None
        self.status = "approved"
    
    def model_dump_for_checkpoint(self) -> dict[str, Any]:
        """
        Returns a checkpoint-safe dictionary representation of the state.
        Suitable for serialization to JSON or other formats.
        """
        return self.model_dump(
            exclude_none=False,
            mode='json',
            serialize_as_any=True,
        )
